### PR TITLE
Added option for Purge Key and Custom Purge Header

### PR DESCRIPTION
**Pull request by jlalvarez18**

### CODE REVIEW

**Comment by maxicus** [comment]
Hi,

Thank you for new functionality. Core idea is fine, but there is one problem with backwards-compatibility when host:port format is used for varnish endpoint parameter you changed.

https://github.com/W3EDGE/w3-total-cache/pull/5/files#diff-4436c0504c83d538b04e3feb771851edR118
Your change requires
http://my-varnish-host:8080/
and doesn't support 
my-varnish-host:8080

Can you add support of "my-varnish-host:8080" please? 
and i'll take your pull request without further modifications.

**Comment by jlalvarez18** [comment]
@maxicus fixed! It now properly parsed the url and adds proper defaults.

**Comment by maxicus** [comment]
Now you violated WordPress Coding Standards:
https://make.wordpress.org/core/handbook/best-practices/coding-standards/php/
"Use real tabs and not spaces, as this allows the most flexibility across clients."

Please fix indentation.

**Comment by maxicus** [comment]
Spaces style is violated too.

And there are new bugs, like
https://github.com/W3EDGE/w3-total-cache/pull/5/files#diff-4436c0504c83d538b04e3feb771851edR135 not passing your header.

**Comment by maxicus** [comment]
I'm sorry you do more and more redundant modifications with each new commit. It was much better at the start.
Please post the pull request with only modifications related to the issue you fix. See the diff your pull request provides for Varnish_Flush.php file.

Also bug introduced by this pull request and mentioned above is not fixed.

**Comment by bwmarkle** [comment]
Hi @jlalvarez18 I'm looking over the PR's for our repo and noticed this one you created over 4 months ago. I'm sorry that the PR hasn't been approved yet, I know you took the time to submit it and go back and forth in a few discussions.

I can bring this one up with the developers again. I just wanted to find out if you had any additional feedback / anything else to add?

Thanks!
\- Brad

**Comment by cssjoe** [comment]
This request is very old and the code is too diverged with conflicts.  If this is still an issue, then a new pull request is recommended; without extra changes for formatting, etc.

**Pull request closed without merging**
